// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderManagement.Persistence.Context;

#nullable disable

namespace OrderManagement.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251121141620_InitialCreate0000000003")]
    partial class InitialCreate0000000003
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("OrderManagement.Domain.Entities.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("city");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("contact");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("full_name");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("postal_code");

                    b.Property<string>("TaxIdentificationNumber")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tax_identification_number");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("OrderManagement.Domain.Entities.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_date");

                    b.Property<long>("CustomerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("customer_id");

                    b.Property<string>("Observations")
                        .HasColumnType("TEXT")
                        .HasColumnName("observations");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("TEXT")
                        .HasColumnName("payment_method");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("OrderManagement.Domain.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("reference");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("REAL")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("OrderManagement.Domain.Entities.ProductOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT")
                        .HasColumnName("color");

                    b.Property<int>("EightYears")
                        .HasColumnType("INTEGER")
                        .HasColumnName("eight_years");

                    b.Property<int>("EighteenMonths")
                        .HasColumnType("INTEGER")
                        .HasColumnName("eighteen_months");

                    b.Property<int>("FourYears")
                        .HasColumnType("INTEGER")
                        .HasColumnName("four_years");

                    b.Property<int>("NineMonths")
                        .HasColumnType("INTEGER")
                        .HasColumnName("nine_months");

                    b.Property<int>("OneMonth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("one_month");

                    b.Property<int>("OneYear")
                        .HasColumnType("INTEGER")
                        .HasColumnName("one_year");

                    b.Property<long>("OrderId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("order_id");

                    b.Property<long>("ProductId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_id");

                    b.Property<int>("SixMonths")
                        .HasColumnType("INTEGER")
                        .HasColumnName("six_months");

                    b.Property<int>("SixYears")
                        .HasColumnType("INTEGER")
                        .HasColumnName("six_years");

                    b.Property<int>("TenYears")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ten_years");

                    b.Property<int>("ThreeMonths")
                        .HasColumnType("INTEGER")
                        .HasColumnName("three_months");

                    b.Property<int>("ThreeYears")
                        .HasColumnType("INTEGER")
                        .HasColumnName("three_years");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("REAL")
                        .HasColumnName("total_price");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_quantity");

                    b.Property<int>("TwelveMonths")
                        .HasColumnType("INTEGER")
                        .HasColumnName("twelve_months");

                    b.Property<int>("TwelveYears")
                        .HasColumnType("INTEGER")
                        .HasColumnName("twelve_years");

                    b.Property<int>("TwentyFourMonths")
                        .HasColumnType("INTEGER")
                        .HasColumnName("twenty_four_months");

                    b.Property<int>("TwoYears")
                        .HasColumnType("INTEGER")
                        .HasColumnName("two_years");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("REAL")
                        .HasColumnName("unit_price");

                    b.Property<int>("ZeroMonths")
                        .HasColumnType("INTEGER")
                        .HasColumnName("zero_months");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("product_order", (string)null);
                });

            modelBuilder.Entity("OrderManagement.Domain.Entities.Order", b =>
                {
                    b.HasOne("OrderManagement.Domain.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("OrderManagement.Domain.Entities.ProductOrder", b =>
                {
                    b.HasOne("OrderManagement.Domain.Entities.Order", "Order")
                        .WithMany("ProductsOrders")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrderManagement.Domain.Entities.Product", "Product")
                        .WithMany("ProductsOrders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OrderManagement.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("OrderManagement.Domain.Entities.Order", b =>
                {
                    b.Navigation("ProductsOrders");
                });

            modelBuilder.Entity("OrderManagement.Domain.Entities.Product", b =>
                {
                    b.Navigation("ProductsOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
