// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderManagement.Persistence.Context;

#nullable disable

namespace OrderManagement.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("OrderManagement.Domain.Entities.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("city");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("contact");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("full_name");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("postal_code");

                    b.Property<string>("TaxIdentificationNumber")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tax_identification_number");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("customers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Address = "Rua das Flores 10",
                            City = "Lisboa",
                            Contact = "912345678",
                            CreatedAt = new DateTime(2025, 11, 7, 23, 34, 50, 860, DateTimeKind.Utc).AddTicks(8634),
                            FullName = "João Silva",
                            PostalCode = "1000-001",
                            TaxIdentificationNumber = "123456789"
                        },
                        new
                        {
                            Id = 2L,
                            Address = "Avenida Central 25",
                            City = "Porto",
                            Contact = "913456789",
                            CreatedAt = new DateTime(2025, 11, 7, 23, 34, 50, 860, DateTimeKind.Utc).AddTicks(8639),
                            FullName = "Maria Santos",
                            PostalCode = "4000-123",
                            TaxIdentificationNumber = "987654321"
                        },
                        new
                        {
                            Id = 3L,
                            Address = "Rua da Liberdade 8",
                            City = "Coimbra",
                            Contact = "914567890",
                            CreatedAt = new DateTime(2025, 11, 7, 23, 34, 50, 860, DateTimeKind.Utc).AddTicks(8640),
                            FullName = "António Santos",
                            PostalCode = "3000-045",
                            TaxIdentificationNumber = "192837465"
                        },
                        new
                        {
                            Id = 4L,
                            Address = "Travessa do Sol 12",
                            City = "Leiria",
                            Contact = "915678901",
                            CreatedAt = new DateTime(2025, 11, 7, 23, 34, 50, 860, DateTimeKind.Utc).AddTicks(8641),
                            FullName = "José Santos",
                            PostalCode = "2400-002",
                            TaxIdentificationNumber = "564738291"
                        });
                });

            modelBuilder.Entity("OrderManagement.Domain.Entities.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<long>("CustomerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("customer_id");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("orders", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2025, 11, 7, 23, 34, 50, 860, DateTimeKind.Utc).AddTicks(8791),
                            CustomerId = 1L,
                            Status = 0
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2025, 11, 7, 23, 34, 50, 860, DateTimeKind.Utc).AddTicks(8794),
                            CustomerId = 2L,
                            Status = 4
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2025, 11, 7, 23, 34, 50, 860, DateTimeKind.Utc).AddTicks(8794),
                            CustomerId = 3L,
                            Status = 1
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2025, 11, 7, 23, 34, 50, 860, DateTimeKind.Utc).AddTicks(8795),
                            CustomerId = 4L,
                            Status = 3
                        });
                });

            modelBuilder.Entity("OrderManagement.Domain.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("reference");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("REAL")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2025, 11, 7, 23, 34, 50, 860, DateTimeKind.Utc).AddTicks(8766),
                            Description = "Camisola de algodão",
                            Reference = "P-1001",
                            UnitPrice = 19.989999999999998
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2025, 11, 7, 23, 34, 50, 860, DateTimeKind.Utc).AddTicks(8769),
                            Description = "Calças de ganga",
                            Reference = "P-1002",
                            UnitPrice = 39.990000000000002
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2025, 11, 7, 23, 34, 50, 860, DateTimeKind.Utc).AddTicks(8770),
                            Description = "Casaco de inverno",
                            Reference = "P-1003",
                            UnitPrice = 59.990000000000002
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2025, 11, 7, 23, 34, 50, 860, DateTimeKind.Utc).AddTicks(8770),
                            Description = "T-shirt básica",
                            Reference = "P-1004",
                            UnitPrice = 9.9900000000000002
                        });
                });

            modelBuilder.Entity("OrderManagement.Domain.Entities.ProductOrder", b =>
                {
                    b.Property<long>("ProductId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_id");

                    b.Property<long>("OrderId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("order_id");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT")
                        .HasColumnName("color");

                    b.Property<int>("EightYears")
                        .HasColumnType("INTEGER")
                        .HasColumnName("eight_years");

                    b.Property<int>("EighteenMonths")
                        .HasColumnType("INTEGER")
                        .HasColumnName("eighteen_months");

                    b.Property<int>("FourYears")
                        .HasColumnType("INTEGER")
                        .HasColumnName("four_years");

                    b.Property<int>("OneMonth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("one_month");

                    b.Property<int>("OneYear")
                        .HasColumnType("INTEGER")
                        .HasColumnName("one_year");

                    b.Property<int>("SixMonths")
                        .HasColumnType("INTEGER")
                        .HasColumnName("six_months");

                    b.Property<int>("SixYears")
                        .HasColumnType("INTEGER")
                        .HasColumnName("six_years");

                    b.Property<int>("TenYears")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ten_years");

                    b.Property<int>("ThirtySixMonths")
                        .HasColumnType("INTEGER")
                        .HasColumnName("thirty_six_months");

                    b.Property<int>("ThreeMonths")
                        .HasColumnType("INTEGER")
                        .HasColumnName("three_months");

                    b.Property<int>("ThreeYears")
                        .HasColumnType("INTEGER")
                        .HasColumnName("three_years");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("REAL")
                        .HasColumnName("total_price");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_quantity");

                    b.Property<int>("TwelveMonths")
                        .HasColumnType("INTEGER")
                        .HasColumnName("twelve_months");

                    b.Property<int>("TwelveYears")
                        .HasColumnType("INTEGER")
                        .HasColumnName("twelve_years");

                    b.Property<int>("TwentyFourMonths")
                        .HasColumnType("INTEGER")
                        .HasColumnName("twenty_four_months");

                    b.Property<int>("TwoYears")
                        .HasColumnType("INTEGER")
                        .HasColumnName("two_years");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("REAL")
                        .HasColumnName("unit_price");

                    b.HasKey("ProductId", "OrderId")
                        .HasName("PK_product_order");

                    b.HasIndex("OrderId");

                    b.ToTable("product_order", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = 1L,
                            OrderId = 1L,
                            Color = "Verde",
                            EightYears = 0,
                            EighteenMonths = 0,
                            FourYears = 0,
                            OneMonth = 2,
                            OneYear = 0,
                            SixMonths = 0,
                            SixYears = 0,
                            TenYears = 0,
                            ThirtySixMonths = 0,
                            ThreeMonths = 1,
                            ThreeYears = 0,
                            TotalPrice = 59.969999999999999,
                            TotalQuantity = 3,
                            TwelveMonths = 0,
                            TwelveYears = 0,
                            TwentyFourMonths = 0,
                            TwoYears = 0,
                            UnitPrice = 19.989999999999998
                        },
                        new
                        {
                            ProductId = 2L,
                            OrderId = 1L,
                            Color = "Azul",
                            EightYears = 0,
                            EighteenMonths = 0,
                            FourYears = 0,
                            OneMonth = 0,
                            OneYear = 0,
                            SixMonths = 1,
                            SixYears = 0,
                            TenYears = 0,
                            ThirtySixMonths = 0,
                            ThreeMonths = 0,
                            ThreeYears = 0,
                            TotalPrice = 119.97,
                            TotalQuantity = 3,
                            TwelveMonths = 2,
                            TwelveYears = 0,
                            TwentyFourMonths = 0,
                            TwoYears = 0,
                            UnitPrice = 39.990000000000002
                        },
                        new
                        {
                            ProductId = 3L,
                            OrderId = 2L,
                            Color = "Vermelho",
                            EightYears = 0,
                            EighteenMonths = 0,
                            FourYears = 0,
                            OneMonth = 0,
                            OneYear = 0,
                            SixMonths = 0,
                            SixYears = 0,
                            TenYears = 0,
                            ThirtySixMonths = 0,
                            ThreeMonths = 0,
                            ThreeYears = 0,
                            TotalPrice = 0.0,
                            TotalQuantity = 0,
                            TwelveMonths = 0,
                            TwelveYears = 0,
                            TwentyFourMonths = 0,
                            TwoYears = 0,
                            UnitPrice = 59.990000000000002
                        },
                        new
                        {
                            ProductId = 4L,
                            OrderId = 2L,
                            Color = "Preto",
                            EightYears = 0,
                            EighteenMonths = 0,
                            FourYears = 0,
                            OneMonth = 0,
                            OneYear = 0,
                            SixMonths = 0,
                            SixYears = 0,
                            TenYears = 0,
                            ThirtySixMonths = 0,
                            ThreeMonths = 0,
                            ThreeYears = 0,
                            TotalPrice = 0.0,
                            TotalQuantity = 0,
                            TwelveMonths = 0,
                            TwelveYears = 0,
                            TwentyFourMonths = 0,
                            TwoYears = 0,
                            UnitPrice = 9.9900000000000002
                        },
                        new
                        {
                            ProductId = 3L,
                            OrderId = 3L,
                            Color = "Branco",
                            EightYears = 0,
                            EighteenMonths = 0,
                            FourYears = 0,
                            OneMonth = 0,
                            OneYear = 0,
                            SixMonths = 0,
                            SixYears = 0,
                            TenYears = 0,
                            ThirtySixMonths = 0,
                            ThreeMonths = 0,
                            ThreeYears = 0,
                            TotalPrice = 0.0,
                            TotalQuantity = 0,
                            TwelveMonths = 0,
                            TwelveYears = 0,
                            TwentyFourMonths = 0,
                            TwoYears = 0,
                            UnitPrice = 59.990000000000002
                        },
                        new
                        {
                            ProductId = 4L,
                            OrderId = 4L,
                            Color = "Cinza",
                            EightYears = 0,
                            EighteenMonths = 0,
                            FourYears = 0,
                            OneMonth = 0,
                            OneYear = 0,
                            SixMonths = 0,
                            SixYears = 0,
                            TenYears = 0,
                            ThirtySixMonths = 0,
                            ThreeMonths = 0,
                            ThreeYears = 0,
                            TotalPrice = 0.0,
                            TotalQuantity = 0,
                            TwelveMonths = 0,
                            TwelveYears = 0,
                            TwentyFourMonths = 0,
                            TwoYears = 0,
                            UnitPrice = 9.9900000000000002
                        });
                });

            modelBuilder.Entity("OrderManagement.Domain.Entities.Order", b =>
                {
                    b.HasOne("OrderManagement.Domain.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("OrderManagement.Domain.Entities.ProductOrder", b =>
                {
                    b.HasOne("OrderManagement.Domain.Entities.Order", "Order")
                        .WithMany("ProductsOrders")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrderManagement.Domain.Entities.Product", "Product")
                        .WithMany("ProductsOrders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OrderManagement.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("OrderManagement.Domain.Entities.Order", b =>
                {
                    b.Navigation("ProductsOrders");
                });

            modelBuilder.Entity("OrderManagement.Domain.Entities.Product", b =>
                {
                    b.Navigation("ProductsOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
